// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc07YIftiiN8rM9mUHJYIm9yqXoriS_Cg',
    appId: '1:169877527306:web:86899343ec6280c6d778f3',
    messagingSenderId: '169877527306',
    projectId: 'mobile-app-dev-a1cc3',
    authDomain: 'mobile-app-dev-a1cc3.firebaseapp.com',
    storageBucket: 'mobile-app-dev-a1cc3.firebasestorage.app',
    measurementId: 'G-W16KWFPTSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvlMNu65wjnRWNaciRCYmApjnySfj_YY',
    appId: '1:169877527306:android:5cb05713f6ca1230d778f3',
    messagingSenderId: '169877527306',
    projectId: 'mobile-app-dev-a1cc3',
    storageBucket: 'mobile-app-dev-a1cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8zSXG9MJwHUlfUyctbmtYEyEd1iZnoM',
    appId: '1:169877527306:ios:70b410f2d20aa793d778f3',
    messagingSenderId: '169877527306',
    projectId: 'mobile-app-dev-a1cc3',
    storageBucket: 'mobile-app-dev-a1cc3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg8zSXG9MJwHUlfUyctbmtYEyEd1iZnoM',
    appId: '1:169877527306:ios:70b410f2d20aa793d778f3',
    messagingSenderId: '169877527306',
    projectId: 'mobile-app-dev-a1cc3',
    storageBucket: 'mobile-app-dev-a1cc3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc07YIftiiN8rM9mUHJYIm9yqXoriS_Cg',
    appId: '1:169877527306:web:4b943d23931ec0e8d778f3',
    messagingSenderId: '169877527306',
    projectId: 'mobile-app-dev-a1cc3',
    authDomain: 'mobile-app-dev-a1cc3.firebaseapp.com',
    storageBucket: 'mobile-app-dev-a1cc3.firebasestorage.app',
    measurementId: 'G-9Q914F6W2R',
  );
}
